# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

# rule_files:
#   - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: current_node
    metrics_path: /metrics
    static_configs:
      - targets:
          - node-exporter:9100
        labels:
          env: lab_works
          role: node

  - job_name: documentstorage_api
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:5161
        labels:
          env: lab_works
          role: web_app
          app: documentstorage_api
