version: '3.7'

services:
  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana_datasources:/etc/grafana/provisioning/datasources
      - ./grafana_data:/var/lib/grafana
    user: "1000"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100

volumes:
  grafana_data:
    external: false
  prometheus_data:
    external: false

networks:
  main:
